services:
  nginx:
    image: "nginxproxy/nginx-proxy:1.6.0"
    container_name: "proxy-nginx"
    restart: always
    environment:
      HTTPS_METHOD: noredirect
      DISABLE_ACCESS_LOGS: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/htpasswd:/etc/nginx/htpasswd
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d
      - ./data/certs/:/etc/nginx/certs
      - ./config/nginx.conf:/etc/nginx/conf.d/proxy.conf:ro
    networks:
      - "pasta"

  acme:
    image: "nginxproxy/acme-companion:2.4.0"
    container_name: "proxy-acme"
    restart: always
    volumes_from:
      - "nginx"
    environment:
      DEFAULT_EMAIL: "$PASTA_EMAIL"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/acme:/etc/acme.sh
    networks:
      - "pasta"

networks:
  pasta:
    external: true