version: "3.7"

services :

  core_gitlab-web:
    image: 'gitlab/gitlab-ce:${GITLAB_IMAGE_VERSION:-latest}'
    restart: unless-stopped
    container_name: core_gitlab-web
    hostname: gitlab.halloumi
    ports:
      - '22:22'
    networks:
      - "halloumi"
    volumes:
      - './data/backups:/var/opt/gitlab/backups'
      - './data/data:/var/opt/gitlab'
      - './data/web-config:/etc/gitlab'
      - './data/logs:/var/log/gitlab'
    environment:
      TZ: Europe/Paris
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.${DOMAIN_NAME}'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['redirect_http_to_https'] = true
        nginx['client_max_body_size'] = "${NGINX_CLIENT_MAX_BODY_SIZE}"
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "${GITLAB_SMTP_ADDRESS}"
        gitlab_rails['smtp_port'] = ${GITLAB_SMTP_PORT}
        gitlab_rails['smtp_user_name'] = "${GITLAB_SMTP_USER_NAME}"
        gitlab_rails['smtp_password'] = "${GITLAB_SMTP_PASSWORD}"
        gitlab_rails['smtp_domain'] = "${GITLAB_SMTP_DOMAIN}"
        gitlab_rails['smtp_authentication'] = "${GITLAB_SMTP_AUTHENTICATION}"
        gitlab_rails['smtp_enable_starttls_auto'] = ${GITLAB_SMTP_STARTTLS_AUTO}
        gitlab_rails['smtp_tls'] = ${GITLAB_SMTP_TLS}
        gitlab_rails['smtp_openssl_verify_mode'] = '${GITLAB_SMTP_OPENSSL_VERIFY_MODE}'
        gitlab_rails['gitlab_email_from'] = '${GITLAB_SMTP_EMAIL_FROM}'
        gitlab_rails['gitlab_email_reply_to'] = '${GITLAB_SMTP_EMAIL_REPLY_TO}'
    shm_size: '256m'

  core_gitlab-runner :
    image: 'gitlab/gitlab-runner:alpine'
    restart: unless-stopped
    container_name: core_gitlab-runner
    networks:
      - "halloumi"
    volumes :
      - './data/runner-config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'

networks:
  halloumi:
    external: true
