networks:
  halloumi:
    external: true

services:
  noco-core:
    image: "nocodb/nocodb:0.207.3"
    container_name: "app_noco-core"
    volumes:
      - "./data/noco-core:/usr/app/data/"
    env_file: ".env"
    environment:
      VIRTUAL_HOST: "noco.$HALLOUMI_DOMAIN"
      LETSENCRYPT_HOST: "noco.$HALLOUMI_DOMAIN"
      VIRTUAL_PORT: 8080
    restart: "always"
    networks:
      - "halloumi"