networks:
  pasta:
    external: true

services:
  umami:
    image: "ghcr.io/umami-software/umami:postgresql-v2.11.3"
    container_name: "app_umami-core"
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@app_umami-postgres:5432/umami"
      DATABASE_TYPE: "postgresql"
      APP_SECRET: "$UMAMI_APP_SECRET"
      VIRTUAL_HOST: "umami.$PASTA_DOMAIN"
      LETSENCRYPT_HOST: "umami.$PASTA_DOMAIN"
      VIRTUAL_PORT: 3000
    depends_on:
      - "postgres"
    restart: "always"
    networks:
      - "pasta"

  postgres:
    image: "postgres:15-alpine"
    container_name: "app_umami-db"
    hostname: "app_umami-postgres"
    environment:
      POSTGRES_DB: "umami"
      POSTGRES_USER: "$POSTGRES_USER"
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
    ports :
      - "5432:5432"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "outline", "-U", "user" ]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: "always"
    networks :
      - "pasta"