networks:
  pasta:
    external: true

services:
  portainer:
    image: "portainer/portainer-ce:latest"
    container_name: "app_portainer-admin"
    restart: "always"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data
    environment:
      VIRTUAL_HOST: "portainer.$PASTA_DOMAIN"
      LETSENCRYPT_HOST: "portainer.$PASTA_DOMAIN"
      VIRTUAL_PORT: 9000
    networks:
      - "pasta"