networks:
  halloumi:
    external: true

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: "app_kuma"
    restart: always
    environment:
      VIRTUAL_HOST: "kuma.$HALLOUMI_DOMAIN"
      LETSENCRYPT_HOST: "kuma.$HALLOUMI_DOMAIN"
      VIRTUAL_PORT: 3001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
    networks:
      - halloumi